### PR TITLE
Make DataProvider extensible

### PR DESCRIPTION
**Pull request by DewaldDeJager**
Use case: As an application developer, I would like to override the `expandParent` and `collapseChilds` methods of the `DataSource` struct so that I can extend the behaviour of the framework

There are a few obstacles to this:
- `DataProvider` is a struct, and therefore cannot be subclassed
- `DataProvider` is `public`, and therefore cannot be subclassed outside of it's module, such as an application pulling this framework in as a dependency
- The implementation of the methods mentioned above are in an extension of `DataSource` which implements the `DataSourceType`. Methods declared in extensions cannot be overriden

What are your thoughts on this? I will make a ticket detailing the behaviour I would like to achieve and hopefully be able to submit a PR with it after getting your thoughts.

Thank you!

### CODE REVIEW

**Comment by DewaldDeJager** [comment]
I have made the ticket detailing what I would like to achieve in Issue https://github.com/Vkt0r/AccordionSwift/issues/54.

**Comment by DewaldDeJager** [comment]
@Vkt0r I am eager to hear your thoughts on this PR.

**Comment by Vkt0r** [comment]
>@Vkt0r I am eager to hear your thoughts on this PR.

@DewaldDeJager Sorry for the delay I’m been very busy during this week. I’m on vacation right now but I’ll take a look on Monday when I go back ! Thanks again for your PR and your patience ! 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Vkt0r** [comment]
@DewaldDeJager I understand your necessity for the overriding of the methods in the extension but actually the protocol `DataSourceType` was created for this specific cases in which you can define your own `DataSource` based in your neccesities.  

Related to the #2 and #54 I think I removed the behavior during the refactor of the library, that's my fault but I would  definitely bring it back without any problem.

**Pull request closed without merging**
